import { Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Image, HelpCircle, Sparkles, ArrowRight } from "lucide-react";
import Footer from "@/components/Footer";
import { getProgress } from "@/lib/progressStore";

const Activities = () => {
  const progress = getProgress();

  const activities = [
    {
      id: "real-or-ai",
      path: "/activities/real-or-ai",
      icon: Image,
      title: "Real or AI?",
      description: "Test your skills by guessing which images are real photographs and which were generated by AI.",
      difficulty: "Easy",
      points: progress.activityScores["real-or-ai"] || 0,
      color: "bg-gradient-to-br from-purple-500 to-blue-500",
    },
    {
      id: "myths-quiz",
      path: "/activities/myths",
      icon: HelpCircle,
      title: "AI Myths & Truths",
      description: "Challenge common misconceptions about AI and learn what's fact versus fiction.",
      difficulty: "Medium",
      points: progress.activityScores["myths-quiz"] || 0,
      color: "bg-gradient-to-br from-cyan-500 to-teal-500",
    },
    {
      id: "build-ai",
      path: "/activities/build-ai",
      icon: Sparkles,
      title: "Build a Mini AI",
      description: "Experience how AI learns by training your own simplified image recognition model.",
      difficulty: "Advanced",
      points: progress.activityScores["build-ai"] || 0,
      color: "bg-gradient-to-br from-orange-500 to-pink-500",
    },
  ];

  return (
    <div className="min-h-screen bg-background">

      <div className="container py-12">
        <div className="max-w-6xl mx-auto space-y-8">
          {/* Header */}
          <div className="text-center space-y-4 animate-fade-in">
            <h1 className="text-4xl font-bold">
              Interactive <span className="bg-gradient-hero bg-clip-text text-transparent">Activities</span>
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Put your AI knowledge to the test with fun, hands-on challenges
            </p>
          </div>

          {/* Activities Grid */}
          <div className="grid md:grid-cols-3 gap-6">
            {activities.map((activity, index) => {
              const Icon = activity.icon;
              return (
                <Card
                  key={activity.id}
                  className="shadow-card hover:shadow-elevated transition-all hover:-translate-y-1 animate-slide-up overflow-hidden"
                  style={{ animationDelay: `${index * 0.1}s` }}
                >
                  <div className={`h-32 ${activity.color} relative`}>
                    <div className="absolute inset-0 flex items-center justify-center">
                      <Icon className="h-16 w-16 text-white/90" />
                    </div>
                  </div>
                  
                  <CardHeader>
                    <div className="flex items-start justify-between mb-2">
                      <CardTitle>{activity.title}</CardTitle>
                      <span className="text-xs font-medium px-2 py-1 rounded-full bg-primary/10 text-primary">
                        {activity.difficulty}
                      </span>
                    </div>
                    <CardDescription>{activity.description}</CardDescription>
                  </CardHeader>

                  <CardContent className="space-y-4">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-muted-foreground">Your Best Score</span>
                      <span className="font-bold text-primary text-lg">
                        {activity.points} pts
                      </span>
                    </div>
                    
                    <Link to={activity.path}>
                      <Button className="w-full gap-2">
                        Start Activity <ArrowRight className="h-4 w-4" />
                      </Button>
                    </Link>
                  </CardContent>
                </Card>
              );
            })}
          </div>

          {/* Tips Card */}
          <Card className="shadow-card bg-gradient-card">
            <CardHeader>
              <CardTitle>Activity Tips 💡</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm text-muted-foreground">
              <p>• Complete activities multiple times to improve your score</p>
              <p>• Read the explanations carefully to learn from mistakes</p>
              <p>• Try "Build a Mini AI" after completing the lessons for best results</p>
              <p>• Earn badges by achieving high scores in each activity</p>
            </CardContent>
          </Card>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default Activities;
